services:
  - type: web
    name: metricmind
    env: node
    plan: starter
    branch: main
    autoDeploy: true
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start

